-- All Exits · Guestbook table + security policies
-- Run this once in Supabase: Dashboard → SQL Editor → New query → paste → Run.

create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

-- Row Level Security: locked down by default, then opened up narrowly.
alter table public.guestbook enable row level security;

-- Anyone (the anon key) can read all messages.
create policy "Public can read guestbook"
  on public.guestbook
  for select
  to anon
  using (true);

-- Anyone (the anon key) can add a message.
create policy "Public can insert guestbook"
  on public.guestbook
  for insert
  to anon
  with check (true);

-- No update/delete policy is created for anon, so visitors can only
-- post and read — never edit or remove a message once it exists.
-- To moderate entries yourself, use the Supabase dashboard's Table
-- Editor (it uses your own login, not the anon key) or the SQL editor,
-- e.g.:  delete from public.guestbook where id = 123;
